---

- name: Personalize by customizing user prompt, hopefully
  become_user: vagrant
  lineinfile:
    dest: ~/.bashrc    
    line: 'PS1="\e[1;34;40m\u@\h: \e[1;31;49m \w \e[1;34;40m\$: \e[0m"'


cd 